name: reusable-test

on:
  workflow_call:
    inputs:
      pull-request-number:
        type: number
        description: A pull request number
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Show input
        run: |
          echo "PR Number: '${{ inputs.pull-request-number }}'"
          echo "Test completed"